replicas = 2
releasename = "test-deployment"

[[container]]
image = "nginx"
tag = "alpine"
name = "web"
command = "/bin/bash -x test.sh"
  [[container.port]]
    name = "http"
    portnum = 80
    protocol = "tcp"
  [[container.port]]
    name = "https"
    portnum = 443
    protocol = "tcp"

[[container]]
image = "nginx"
tag = "latest"
name = "web1"
command = "/bin/bash -x test2.sh"
  [[container.port]]
    name = "http"
    portnum = 80
    protocol = "tcp"
  [[container.port]]
    name = "https"
    portnum = 443
    protocol = "tcp"

[[label]]
key = "app"
value = "test-deploy"

[[label]]
key = "region"
value = "us-east-1"
